name: auto repo creation
on: 
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: auto repo creator on pull request
        uses: sarthakjdev/auto-repo-creator-on-pullRequest@v0.0
        with:
          organization: workflow-testing-org
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    env:
         TOKEN: ${{ secrets.TOKEN }}

