name: auto repo creation
on: 
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: auto repo creator on pull request
        uses: sarthakjdev/autorepo-create-on-pullrequest@pre-release-test-9
        with:
          organization: workflow-testing-org
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    env:
         TOKEN: ${{ secrets.TOKEN }}
