name: auto repo creation
on: 
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: private repo creation
        uses: sarthakjdev/autorepo-create-on-pullrequest@pre-release-test-4
        with:
          organization: workflow-testing-org
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    env:
         TOKEN: ${{ secrets.TOKEN }}

